# Generated by Django 5.0.1 on 2024-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='approved',
        ),
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
