# Generated by Django 5.0.1 on 2024-07-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_myrating_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyRating',
        ),
    ]
