# Generated by Django 5.0.1 on 2024-07-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_delete_myrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
