# Generated by Django 5.0.1 on 2024-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_reward_order_points_earned_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='available',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.AddField(
            model_name='reward',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='points_required',
            field=models.IntegerField(),
        ),
    ]
