# Generated by Django 5.0.1 on 2024-07-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_remove_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
