# Generated by Django 5.0.1 on 2024-07-20 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
