# Generated by Django 5.0.1 on 2024-07-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0025_table_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
